.\" (C) Copyright 2021 LanjieYou <ylj18926385312@163.com>,
.TH Cgame3 6 "October  1 2021"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH 名字
cgame3 \- 贪吃蛇游戏
\" .SH 说明
\" .B cgame3
\" .RI [ options ] " files" ...
\" .br
.SH 描述
.B cgame3
是一个用c语言编写的
.B 贪吃蛇
小游戏
.PP
.SH 操作
方向键控制蛇的方向
.PP
场地的大小由窗口大小决定
.PP
碰到边缘或吃掉自己游戏就会结束
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\" .SH 选项
\" .TP
\" .B \-h, \-\-help
\" Show summary of options.
\" .TP
\" .B \-v, \-\-version
\" Show version of program.
